blank_issues_enabled: false
contact_links:
  - name: ArkManager 论坛
    url: https://f.yistars.net/
    about: 获取更快捷的回复
  - name: ArkManager Forum
    url: https://f.yistars.net/
    about: Get quicker responses
